# Source Databricks Workspace
SOURCE_WORKSPACE_URI = '{WORKSPACE_URI}'
SOURCE_PERSONAL_TOKEN = '{TOKEN}'
SOURCE_USER = '{USER_EMAIL}'
SOURCE_LOCAL_DIR = '{YOUR_LOCAL_DRIVE}'
SOURCE_WORKSPACE_PATH = f"/Users/{SOURCE_USER}/"


# Destination Databricks Workspace
DESTINATION_WORKSPACE_URI = '{WORKSPACE_URI}'
DESTINATION_PERSONAL_TOKEN = '{TOKEN}'
DESTINATION_USER = '{USER_EMAIL}'
DESTINATION_LOCAL_DIR = '{YOUR_LOCAL_DRIVE}'
DESTINATION_WORKSPACE_PATH = f"/Users/{DESTINATION_USER}/"


